console.log("===============Assignment no 1 nikhilsapkal================");
console.log("***************Step 1*****************");
console.log("My dream Company is Tata Consultancy Services");
console.log("**************Step 2******************");
var hobby1 = " Programming.";
var hobby2 = " Riding-Bike.";
var hobby3 = " Travelling.";
console.log(`hobby1 : , ${hobby1}, hobby2 : , ${hobby2} hobby3 : , ${hobby3}`);
console.log("**************Step 3******************");
var addition = hobby1.concat(hobby2).concat(hobby3);
console.log(`Result of String concatenantion is :  ${addition}`);                
